# In-Class Programming Activity, Day 5

Your work goes here ...



## Test statements
Task 1
```{r}
library("mosaicData", lib.loc="~/R/library")
installed.packages("mosaicData")
nbins <- 10
```

task 2
```{r}
evenly_spaced <- seq(min(Galton$height), max(Galton$height), 
                     length = nbins +1)

```
task 3
```{r}
bin_counts <- cut(Galton$height, evenly_spaced)
bin_counts<- table(bin_counts)
```
```{r}
hist_basics <- data.frame(
  xL = evenly_spaced[-length(evenly_spaced)],
  xR = evenly_spaced[-1],
  count = as.numeric(bin_counts))
hist_basics

```
```{r}
make_one_bar <- function(point) {
  xLeft <- point$xL
  xRight <- point$xR
  height <- point$count
  res <- data.frame(
              x = c(xLeft,  xLeft,  xRight, xRight, NA),
              y = c(    0, height,  height,      0, NA)
  )
  return(res)
}
one_to_five <- function(hist_data) {
  bars <- NULL
  for (k in 1:nrow(hist_data)) {
    new_bar <- make_one_bar(hist_data[k, ])
    bars <- rbind(bars, new_bar)
  }
  return(bars)
}

My_bars <- one_to_five(hist_basics)
plot(My_bars, type = "n")
lines(My_bars)
polygon(My_bars)
```


```{r}
scoreActivity::score253(5)
```