# In-Class Programming Activity, Day 6

Your work goes here ...


Connor Doak
## Test statements
```{r}
myHistogram <- function(data, nbins = 10, fill = "blue"){
  
  evenly_spaced <- seq(min(data), max(data), 
                       length = nbins +1)
  
  
  bin_counts <- cut(data, evenly_spaced)
  bin_counts<- table(bin_counts)
  
  hist_basics <- data.frame(
    xL = evenly_spaced[-length(evenly_spaced)],
    xR = evenly_spaced[-1],
    count = as.numeric(bin_counts))
  
  
  make_one_bar <- function(point) {
    xLeft <- point$xL
    xRight <- point$xR
    height <- point$count
    res <- data.frame(
      x = c(xLeft,  xLeft,  xRight, xRight, NA),
      y = c(    0, height,  height,      0, NA)
    )
    return(res)
  }
  one_to_five <- function(hist_data) {
    bars <- NULL
    for (k in 1:nrow(hist_data)) {
      new_bar <- make_one_bar(hist_data[k, ])
      bars <- rbind(bars, new_bar)
    }
    return(bars)
  }
  
  My_bars <- one_to_five(hist_basics)
  plot(My_bars, type = "l")
  polygon(My_bars, col = fill)
  
  seqx <- seq(min(evenly_spaced), max(evenly_spaced), length = 100)
  densy <- dnorm(seqx, mean = mean(data), sd = sd(data))
  totArea <- sum(bin_counts*(evenly_spaced[2]-evenly_spaced[1]))
  lines(seqx, densy*totArea, col = "red")
}
```

```{r}
myHistogram(mtcars$hp)


```
```{r}
v <- rnorm(10, mean=100, sd=1)
x <- dnorm(v)
#bw <- bandwidth.kernel()
kernel <- function(input){
  dnorm(input)
  Dvals <- outer(v, x, FUN = kernel)
}


```

```{r}
plotdensity <- function(v, data=parent.frame(), ...) {
  v <- substitute(v) 
  vname <- as.character(v)
  vvals <- eval(v, envir = data)
  
}
```


```{r}
scoreActivity::score253(6)
```