# Topic 3 Exercises: Likelihood

Connor Doak

```{r}
vals <- rexp(100, 1/100)
#vals
#task 2
test200 <- dexp(vals, rate = 1/200, log = TRUE)
#test200
sum(test200)
```

```{r}
LL_exp <- function(rate){
  sum(dexp(vals, rate, log = TRUE))
  }
LL_exp(1/200)
rates <- c(1/200:1/50)
results <- sapply(rates, LL_exp)
results
```
```{r}
plot(1/rates, results)
max(1/rates)
exp_results <- optimize(LL_exp, 
                        lower=1/200, upper=1/50,
                        maximum = TRUE)
exp_results
```
Programming activity 8
```{r}
x = runif(100, min = 20, max = 70)
My_data <- data.frame(x=x, 
                      y = 5+3*x + 2*rnorm(100))
plot(My_data)
#2
LL_lines <- function(params){
  m = params[1]
  b = params[2]
  sigma = params[3]
  sum(log(dnorm(My_data$y - (m * My_data$x + b), sd = sigma)))
}
#4
testA <- c(3,5,2)
testB <- c(4,1,10)
LL_lines(testA)
LL_lines(testB)
#5
starting_params <- c(4, 1, 10)
best <- optim(starting_params, LL_lines, control=list(fnscale = -1))
best
```

```{r}
load(url("http://tiny.cc/dcf/Taxi_trips.rda"))
waiting_fare <- Taxi_trips$fare_amount - (Taxi_trips$base_fare + Taxi_trips$per_mile*Taxi_trips$trip_distance)
waitvals <- dexp(waiting_fare)

taxi_likelihood <- function(params){
  base_fare = params[1]
  per_mile = params[2]
  param = params[3]
  sum(log(dexp(Taxi_trips$fare_amount-(base_fare
                                       +per_mile*params))))
}
 

testtaxi <- c(base_fare = 1, per_mile = 1, params = 1/3)
taxi_likelihood(testtaxi)
best <- optim(testtaxi, taxi_likelihood, control=list(fnscale = -1))
best
plot(Taxi_trips$fare_amount~Taxi_trips$trip_distance)
reg <- lm(Taxi_trips$fare_amount ~Taxi_trips$trip_distance)
abline(reg, col = "red")
```

